/**
 * Development seed.
 *
 * Creates two accounts and a spread of messages across every delivery state so
 * the dashboards have something to render on a fresh clone. Every network trace
 * is synthetic but shaped like a real one — the phase proportions match what an
 * actual transaction against a local relay produces, so the waterfall looks
 * right rather than uniform.
 *
 * Idempotent: re-running replaces the seeded data instead of duplicating it.
 */
import { randomUUID } from 'node:crypto';
import type { SmtpPhase } from '@postal/shared';
import { env } from '../config/env.js';
import { logger } from '../config/logger.js';
import { connectToDatabase, disconnectFromDatabase } from './connection.js';
import { MessageModel } from '../models/message.model.js';
import { UserModel } from '../models/user.model.js';
import { RefreshTokenModel } from '../models/refresh-token.model.js';
import { hashPassword } from '../modules/auth/password.js';

const DEMO_PASSWORD = 'PostalDemo123!';

const SUBJECTS = [
  'Lab report — congestion control measurements',
  'Re: TLS handshake latency on the campus relay',
  'Weekly delivery summary',
  'MX failover test results',
  'Attachment throughput benchmark',
  'Re: greylisting on the secondary MX',
  'Queue depth alert threshold',
  'Postmortem: deferred mail backlog',
];

async function seed(): Promise<void> {
  await connectToDatabase();

  const passwordHash = await hashPassword(DEMO_PASSWORD);
  const accounts = [
    { email: `demo@${env.MAIL_DOMAIN}`, displayName: 'Demo User', mailbox: 'demo', role: 'user' },
    { email: `admin@${env.MAIL_DOMAIN}`, displayName: 'Operator', mailbox: 'admin', role: 'admin' },
  ];

  const emails = accounts.map((a) => a.email);
  const existing = await UserModel.find({ email: { $in: emails } }).select('_id').lean();
  if (existing.length > 0) {
    await MessageModel.deleteMany({ owner: { $in: existing.map((u) => u._id) } });
    await RefreshTokenModel.deleteMany({ user: { $in: existing.map((u) => u._id) } });
    await UserModel.deleteMany({ _id: { $in: existing.map((u) => u._id) } });
    logger.info({ count: existing.length }, 'Removed previously seeded accounts');
  }

  const users = await UserModel.create(accounts.map((a) => ({ ...a, passwordHash })));
  const [demo, admin] = users;
  if (!demo || !admin) throw new Error('Seed failed to create accounts');

  const messages: Record<string, unknown>[] = [];

  // Outbound mail across every terminal and in-flight state.
  for (let i = 0; i < 40; i += 1) {
    const status = pickStatus(i);
    const createdAt = new Date(Date.now() - i * 37 * 60 * 1000);
    const settled = status === 'sent' || status === 'failed';

    messages.push({
      owner: demo._id,
      messageId: `<${randomUUID()}@${env.MAIL_DOMAIN}>`,
      folder: 'sent',
      status,
      from: demo.email,
      to: [`peer${i % 5}@example.net`],
      cc: i % 7 === 0 ? [admin.email] : [],
      bcc: [],
      subject: SUBJECTS[i % SUBJECTS.length]!,
      body: `Message ${i + 1} generated by the Postal seed script.\n\nStatus: ${status}.`,
      html: false,
      read: true,
      starred: i % 9 === 0,
      attemptCount: status === 'queued' ? 0 : 1,
      lastError: status === 'failed' ? '550 5.1.1 Recipient address rejected: User unknown' : null,
      nextRetryAt: status === 'deferred' ? new Date(Date.now() + 60_000) : null,
      attempts: settled || status === 'deferred' ? [syntheticAttempt(status, createdAt)] : [],
      createdAt,
      updatedAt: createdAt,
    });
  }

  // Inbound mail, as the ingress daemon would have filed it.
  for (let i = 0; i < 12; i += 1) {
    const createdAt = new Date(Date.now() - i * 53 * 60 * 1000);
    messages.push({
      owner: demo._id,
      messageId: `<${randomUUID()}@example.net>`,
      folder: 'inbox',
      status: 'sent',
      from: `sender${i % 4}@example.net`,
      to: [demo.email],
      cc: [],
      bcc: [],
      subject: SUBJECTS[(i + 3) % SUBJECTS.length]!,
      body: `Inbound message ${i + 1}, received over SMTP.`,
      html: false,
      read: i % 3 !== 0,
      starred: i % 5 === 0,
      attemptCount: 0,
      attempts: [],
      createdAt,
      updatedAt: createdAt,
    });
  }

  // `insertMany` bypasses the `pre('save')` hook that derives preview and size,
  // so those are computed here rather than left empty.
  for (const message of messages) {
    const body = message.body as string;
    message.bodyPreview = body.replace(/\s+/g, ' ').trim().slice(0, 180);
    message.sizeBytes = Buffer.byteLength(body, 'utf8');
  }

  await MessageModel.insertMany(messages);

  logger.info(
    { users: users.length, messages: messages.length },
    'Seed complete',
  );
  // eslint-disable-next-line no-console -- credentials are the point of this script
  console.log(
    `\n  Seeded accounts (password: ${DEMO_PASSWORD})\n` +
      accounts.map((a) => `    • ${a.email}  [${a.role}]`).join('\n') +
      '\n',
  );
}

function pickStatus(index: number): 'sent' | 'failed' | 'deferred' | 'queued' {
  // Roughly 80% delivered, which is what a healthy relay looks like — a uniform
  // split would make the delivery-rate tile read as a permanent incident.
  if (index % 17 === 0) return 'queued';
  if (index % 11 === 0) return 'deferred';
  if (index % 7 === 0) return 'failed';
  return 'sent';
}

function syntheticAttempt(status: string, at: Date): Record<string, unknown> {
  const phases: { phase: SmtpPhase; durationMs: number }[] = [
    { phase: 'dns', durationMs: jitter(12, 0.6) },
    { phase: 'tcp', durationMs: jitter(18, 0.5) },
    { phase: 'tls', durationMs: jitter(46, 0.4) },
    { phase: 'greeting', durationMs: jitter(24, 0.7) },
    { phase: 'ehlo', durationMs: jitter(9, 0.5) },
    { phase: 'mailFrom', durationMs: jitter(8, 0.5) },
    { phase: 'rcptTo', durationMs: jitter(11, 0.5) },
    { phase: 'data', durationMs: jitter(63, 0.8) },
    { phase: 'quit', durationMs: jitter(5, 0.4) },
  ];

  const totalMs = round(phases.reduce((sum, p) => sum + p.durationMs, 0));
  const messageBytes = Math.round(jitter(2400, 0.5));

  return {
    attempt: 1,
    startedAt: at,
    finishedAt: new Date(at.getTime() + totalMs),
    status,
    responseCode: status === 'sent' ? 250 : status === 'failed' ? 550 : 451,
    responseText:
      status === 'sent'
        ? '2.0.0 Ok: queued'
        : status === 'failed'
          ? '5.1.1 Recipient address rejected'
          : '4.7.1 Greylisted, try again later',
    error: status === 'sent' ? null : 'Remote server rejected the message',
    trace:
      status === 'sent'
        ? {
            remoteHost: 'mx1.example.net',
            remoteAddress: '203.0.113.25',
            remotePort: 25,
            mxPriority: 10,
            tlsProtocol: 'TLSv1.3',
            tlsCipher: 'TLS_AES_256_GCM_SHA384',
            totalMs,
            phases,
            messageBytes,
            throughputKbps: round(
              (messageBytes * 8) / (phases.find((p) => p.phase === 'data')?.durationMs ?? 1),
            ),
            client: null,
          }
        : null,
  };
}

function jitter(base: number, spread: number): number {
  return round(base * (1 + (Math.random() - 0.5) * 2 * spread));
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

seed()
  .then(() => disconnectFromDatabase())
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    logger.fatal({ err: error }, 'Seed failed');
    process.exit(1);
  });
